version: "3.9"
services:
  detection-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"

# version: "3.9"
# services:
#   api:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#       target: develop
#     command: ["--host", "0.0.0.0", "app.main:app", "--reload"]
#     ports:
#     - "8000:8000"
#     restart: on-failure